spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    database-platform: org.hibernate.dialect.postgresqldialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-176-34-97-213.eu-west-1.compute.amazonaws.com:5432/d1htngarsh95ut
    username: qiyzrgvdgacdyz
    password: b49fbff7cb2f0f538309f467192baff7792b89a4997533e3d217e467b206ef2e
    #url: jdbc:postgresql://localhost:5432/student_assistant_bot_db
    #username: postgres
    #password: DShmatkov
    driverClassName: org.postgresql.Driver
    initialization-mode:

