spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-176-34-97-213.eu-west-1.compute.amazonaws.com/d1htngarsh95ut
    username: qiyzrgvdgacdyz
    password: b49fbff7cb2f0f538309f467192baff7792b89a4997533e3d217e467b206ef2e
    driverClassName: org.postgresql.Driver